### ISSUE TITLE
Fix alignment issue of feature callouts on the homepage

### ISSUE THREAD

**Issue by DEV-SOUTH** [DEVSOUTH/PG#3]
Get these vertically aligned.

![screen shot 2017-10-09 at 1 21 44 pm](https://user-images.githubusercontent.com/7863309/31350345-d0b13b44-acf4-11e7-8f0a-8dde04cc1930.png)

**Comment by tim0thius** [comment]
![image](https://user-images.githubusercontent.com/9800796/31557724-94523482-b00f-11e7-984d-fc84ee33f0cd.png)
I updated it locally to look like the attached image. Also added some guides here to see vertical alignment more clearly. Right now there is a bit of an optical illusion going on because "Gym Owner" is pushed up to make room for the word "monthly".  Are they wanting the vertical alignment adjusted to be mathematically correct or to _feel_ correct (which would require pushing the GOM logo down more than the rest)?

**Comment by DEV-SOUTH** [comment]
What you have attached here will work.
